/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.minigroup1.view;

import com.mycompany.minigroup1.model.TinNhan;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author azoom
 */
public class GiaoDienGroup2 extends javax.swing.JFrame {

    /**
     * Creates new form GiaoDienGroup2
     */
    public GiaoDienGroup2() {
        initComponents();
    }
    
    public void themCommentVaoPanelComment(TinNhan tinNhan1){
        GiaoDien1TinNhan giaoDienTinNhan1= new GiaoDien1TinNhan(tinNhan1);
        this.KhungChuaTinNhanjPanel5.add(giaoDienTinNhan1);
        this.KhungChuaTinNhanjPanel5.add(giaoDienTinNhan1);
        this.KhungChuaTinNhanjPanel5.add(giaoDienTinNhan1);
        this.KhungChuaTinNhanjPanel5.add(giaoDienTinNhan1);
        this.KhungChuaTinNhanjPanel5.add(giaoDienTinNhan1);
        this.KhungChuaTinNhanjPanel5.add(giaoDienTinNhan1);
        
        
        this.KhungChuaTinNhanjPanel5.revalidate();
        this.KhungChuaTinNhanjPanel5.repaint();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VungChinh_jPanel1 = new javax.swing.JPanel();
        KhungChuaTinNhan_jScrollPane1 = new javax.swing.JScrollPane();
        KhungChuaTinNhanjPanel5 = new javax.swing.JPanel();
        jSeparator8 = new javax.swing.JSeparator();
        KhungSoanTinNhan_jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jButton3 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        ThanhBen_jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        KhungChuaID_jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        KhungChuaThongTinGroup_jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        ListMember_jScrollPane3 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.X_AXIS));

        VungChinh_jPanel1.setLayout(new javax.swing.BoxLayout(VungChinh_jPanel1, javax.swing.BoxLayout.Y_AXIS));

        KhungChuaTinNhan_jScrollPane1.setBorder(null);

        KhungChuaTinNhanjPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout KhungChuaTinNhanjPanel5Layout = new javax.swing.GroupLayout(KhungChuaTinNhanjPanel5);
        KhungChuaTinNhanjPanel5.setLayout(KhungChuaTinNhanjPanel5Layout);
        KhungChuaTinNhanjPanel5Layout.setHorizontalGroup(
            KhungChuaTinNhanjPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 569, Short.MAX_VALUE)
        );
        KhungChuaTinNhanjPanel5Layout.setVerticalGroup(
            KhungChuaTinNhanjPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 323, Short.MAX_VALUE)
        );

        KhungChuaTinNhan_jScrollPane1.setViewportView(KhungChuaTinNhanjPanel5);

        VungChinh_jPanel1.add(KhungChuaTinNhan_jScrollPane1);

        jSeparator8.setMaximumSize(new java.awt.Dimension(32767, 10));
        jSeparator8.setPreferredSize(new java.awt.Dimension(0, 10));
        jSeparator8.setVerifyInputWhenFocusTarget(false);
        VungChinh_jPanel1.add(jSeparator8);

        KhungSoanTinNhan_jPanel6.setLayout(new javax.swing.BoxLayout(KhungSoanTinNhan_jPanel6, javax.swing.BoxLayout.X_AXIS));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(null);
        jScrollPane1.setViewportView(jTextArea1);

        KhungSoanTinNhan_jPanel6.add(jScrollPane1);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setMaximumSize(new java.awt.Dimension(10, 32767));
        jSeparator1.setMinimumSize(new java.awt.Dimension(10, 10));
        jSeparator1.setName(""); // NOI18N
        jSeparator1.setPreferredSize(new java.awt.Dimension(10, 10));
        KhungSoanTinNhan_jPanel6.add(jSeparator1);

        jButton3.setText("Send");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        KhungSoanTinNhan_jPanel6.add(jButton3);

        VungChinh_jPanel1.add(KhungSoanTinNhan_jPanel6);

        getContentPane().add(VungChinh_jPanel1);

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator5.setMaximumSize(new java.awt.Dimension(10, 32767));
        jSeparator5.setPreferredSize(new java.awt.Dimension(10, 0));
        getContentPane().add(jSeparator5);

        ThanhBen_jScrollPane2.setBorder(null);

        jPanel2.setToolTipText("");
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        KhungChuaID_jPanel3.setMaximumSize(new java.awt.Dimension(220, 70));
        KhungChuaID_jPanel3.setMinimumSize(new java.awt.Dimension(220, 70));
        KhungChuaID_jPanel3.setName(""); // NOI18N
        KhungChuaID_jPanel3.setPreferredSize(new java.awt.Dimension(220, 70));
        KhungChuaID_jPanel3.setLayout(new java.awt.GridLayout(1, 2));

        jLabel2.setText("Your ID : ");
        KhungChuaID_jPanel3.add(jLabel2);
        KhungChuaID_jPanel3.add(jLabel7);

        jPanel2.add(KhungChuaID_jPanel3);

        jSeparator4.setMaximumSize(new java.awt.Dimension(32767, 10));
        jSeparator4.setPreferredSize(new java.awt.Dimension(0, 10));
        jSeparator4.setVerifyInputWhenFocusTarget(false);
        jPanel2.add(jSeparator4);

        KhungChuaThongTinGroup_jPanel5.setMaximumSize(new java.awt.Dimension(220, 70));
        KhungChuaThongTinGroup_jPanel5.setMinimumSize(new java.awt.Dimension(220, 70));
        KhungChuaThongTinGroup_jPanel5.setName(""); // NOI18N
        KhungChuaThongTinGroup_jPanel5.setPreferredSize(new java.awt.Dimension(220, 70));
        KhungChuaThongTinGroup_jPanel5.setLayout(new java.awt.GridLayout(3, 2));

        jLabel6.setText("Dia chi server");
        KhungChuaThongTinGroup_jPanel5.add(jLabel6);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        KhungChuaThongTinGroup_jPanel5.add(jTextField3);

        jLabel8.setText("Port server");
        KhungChuaThongTinGroup_jPanel5.add(jLabel8);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        KhungChuaThongTinGroup_jPanel5.add(jTextField2);

        jButton4.setText("Join group");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        KhungChuaThongTinGroup_jPanel5.add(jButton4);

        jButton2.setText("Leave group");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        KhungChuaThongTinGroup_jPanel5.add(jButton2);

        jPanel2.add(KhungChuaThongTinGroup_jPanel5);

        jSeparator6.setMaximumSize(new java.awt.Dimension(32767, 10));
        jSeparator6.setPreferredSize(new java.awt.Dimension(0, 10));
        jSeparator6.setVerifyInputWhenFocusTarget(false);
        jPanel2.add(jSeparator6);

        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.Y_AXIS));

        jLabel4.setText("List member");
        jPanel4.add(jLabel4);

        jSeparator7.setMaximumSize(new java.awt.Dimension(32767, 10));
        jSeparator7.setPreferredSize(new java.awt.Dimension(0, 10));
        jSeparator7.setVerifyInputWhenFocusTarget(false);
        jPanel4.add(jSeparator7);

        ListMember_jScrollPane3.setViewportView(jPanel4);

        jPanel2.add(ListMember_jScrollPane3);

        ThanhBen_jScrollPane2.setViewportView(jPanel2);

        getContentPane().add(ThanhBen_jScrollPane2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDienGroup2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDienGroup2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDienGroup2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDienGroup2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GiaoDienGroup2 giaoDienGroup21= new GiaoDienGroup2();
                giaoDienGroup21.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel KhungChuaID_jPanel3;
    private javax.swing.JPanel KhungChuaThongTinGroup_jPanel5;
    private javax.swing.JScrollPane KhungChuaTinNhan_jScrollPane1;
    private javax.swing.JPanel KhungChuaTinNhanjPanel5;
    private javax.swing.JPanel KhungSoanTinNhan_jPanel6;
    private javax.swing.JScrollPane ListMember_jScrollPane3;
    private javax.swing.JScrollPane ThanhBen_jScrollPane2;
    private javax.swing.JPanel VungChinh_jPanel1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
