/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.minigroup1.view;

import com.mycompany.minigroup1.model.TinNhan;

/**
 *
 * @author azoom
 */
public class GiaoDien1TinNhan extends javax.swing.JPanel {
    TinNhan tinNhan;
    /**
     * Creates new form GiaoDienTinNhan
     */
    public GiaoDien1TinNhan(TinNhan tinNhan) {
        initComponents();
        this.tinNhan= tinNhan;
        this.idClient_jLabel1.setText("From : "+ this.tinNhan.getIdNguoiGui());
        this.noiDungComment_jTextArea1.setText(this.tinNhan.getNoiDungTinNhan());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idClient_jLabel1 = new javax.swing.JLabel();
        noiDungComment_jScrollPane1 = new javax.swing.JScrollPane();
        noiDungComment_jTextArea1 = new javax.swing.JTextArea();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        idClient_jLabel1.setText("From :");
        add(idClient_jLabel1);

        noiDungComment_jTextArea1.setColumns(20);
        noiDungComment_jTextArea1.setRows(5);
        noiDungComment_jTextArea1.setPreferredSize(new java.awt.Dimension(150, 84));
        noiDungComment_jScrollPane1.setViewportView(noiDungComment_jTextArea1);

        add(noiDungComment_jScrollPane1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel idClient_jLabel1;
    private javax.swing.JScrollPane noiDungComment_jScrollPane1;
    private javax.swing.JTextArea noiDungComment_jTextArea1;
    // End of variables declaration//GEN-END:variables
    

}
